name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6

      - name: Install dependencies
        run: pnpm install

      - name: Output .env
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          APP_ID: ${{ secrets.APP_ID }}
          APP_SECRET: ${{ secrets.APP_SECRET }}
        run: |
          echo "DATABASE_URL=$DATABASE_URL" >> .env
          echo "APP_ID=$APP_ID" >> .env
          echo "APP_SECRET=$APP_SECRET" >> .env

      - name: Run tests
        run: npm test
